//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace taskApi13_2_2023.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class specialization
    {
        public int specialization_id { get; set; }
        public Nullable<int> faculty_id { get; set; }
        public string MajorName { get; set; }
    
        public virtual Faculty Faculty { get; set; }
    }
}
